# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobufs/csgo.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'protobufs/csgo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protobufs/csgo.proto\"X\n\x16PlayerCommendationInfo\x12\x14\n\x0c\x63md_friendly\x18\x01 \x01(\r\x12\x14\n\x0c\x63md_teaching\x18\x02 \x01(\r\x12\x12\n\ncmd_leader\x18\x04 \x01(\r\"O\n\x0f\x41\x63\x63ountActivity\x12\x10\n\x08\x61\x63tivity\x18\x01 \x01(\r\x12\x0c\n\x04mode\x18\x02 \x01(\r\x12\x0b\n\x03map\x18\x03 \x01(\r\x12\x0f\n\x07matchid\x18\x04 \x01(\x04\"q\n\x11PlayerRankingInfo\x12\x12\n\naccount_id\x18\x01 \x01(\r\x12\x0f\n\x07rank_id\x18\x02 \x01(\r\x12\x0c\n\x04wins\x18\x03 \x01(\r\x12\x13\n\x0brank_change\x18\x04 \x01(\x02\x12\x14\n\x0crank_type_id\x18\x06 \x01(\r\"\xec\x01\n\x10MatchmakingHello\x12\x12\n\naccount_id\x18\x01 \x01(\r\x12\x17\n\x0fpenalty_seconds\x18\x04 \x01(\r\x12\x16\n\x0epenalty_reason\x18\x05 \x01(\r\x12\x12\n\nvac_banned\x18\x06 \x01(\x05\x12#\n\x07ranking\x18\x07 \x01(\x0b\x32\x12.PlayerRankingInfo\x12-\n\x0c\x63ommendation\x18\x08 \x01(\x0b\x32\x17.PlayerCommendationInfo\x12\x14\n\x0cplayer_level\x18\x11 \x01(\x05\x12\x15\n\rplayer_cur_xp\x18\x12 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.csgo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAYERCOMMENDATIONINFO']._serialized_start=24
  _globals['_PLAYERCOMMENDATIONINFO']._serialized_end=112
  _globals['_ACCOUNTACTIVITY']._serialized_start=114
  _globals['_ACCOUNTACTIVITY']._serialized_end=193
  _globals['_PLAYERRANKINGINFO']._serialized_start=195
  _globals['_PLAYERRANKINGINFO']._serialized_end=308
  _globals['_MATCHMAKINGHELLO']._serialized_start=311
  _globals['_MATCHMAKINGHELLO']._serialized_end=547
# @@protoc_insertion_point(module_scope)
